# Generated by Django 5.0.2 on 2024-03-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sender_review_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sender',
        ),
    ]